// src/realtime/stores/chatActions.js
// Action types for chat store

export const CHAT_ACTIONS = {
  INIT_CONVERSATIONS_FROM_API: 'INIT_CONVERSATIONS_FROM_API',
  INIT_MESSAGES_FOR_CONVERSATION: 'INIT_MESSAGES_FOR_CONVERSATION',
  SET_ACTIVE_CONVERSATION: 'SET_ACTIVE_CONVERSATION',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  MESSAGE_UPDATED: 'MESSAGE_UPDATED',
  MESSAGE_DELETED: 'MESSAGE_DELETED',
  RECEIVE_READ_RECEIPT: 'RECEIVE_READ_RECEIPT',
  STAFF_CHAT_READ_RECEIPT_RECEIVED: 'STAFF_CHAT_READ_RECEIPT_RECEIVED',
  MARK_CONVERSATION_READ: 'MARK_CONVERSATION_READ',
  UPDATE_CONVERSATION_METADATA: 'UPDATE_CONVERSATION_METADATA'
};